[connection]

[[usb_device]]
vid = "303a"
pid = "80d7"

[[usb_device]]
vid = "303a"
pid = "1001"

[[usb_device]]
vid = "303a"
pid = "4001"

[[usb_device]]
vid = "1a86"
pid = "55d3"

[flash]
size = "8MB"
